fail_fast: true
repos:
  # general
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Use the ref you want to point at
    # https://github.com/pre-commit/pre-commit-hooks#hooks-available
    hooks:
      - id: check-added-large-files # Prevent giant files from being committed.
      - id: check-docstring-first # Checks for a common error of placing code before the docstring.
      - id: check-executables-have-shebangs # Checks that non-binary executables have a proper shebang.
      - id: check-json # Attempts to load all json files to verify syntax.
      - id: check-merge-conflict # Check for files that contain merge conflict strings.
      - id: check-shebang-scripts-are-executable # Checks that scripts with shebangs are executable.
      - id: check-symlinks # Checks for symlinks which do not point to anything.
      - id: check-toml # Attempts to load all TOML files to verify syntax.
      - id: check-xml # Attempts to load all xml files to verify syntax.
      - id: check-yaml # Attempts to load all yaml files to verify syntax.
      - id: detect-private-key # Checks for the existence of private keys.
      - id: end-of-file-fixer # Makes sure files end in a newline and only a newline.
      - id: name-tests-test # verifies that test files are named correctly.
      - id: requirements-txt-fixer # Sorts entries in requirements.txt and constraints.txt and removes incorrect entry for pkg-resources==0.0.0
      - id: trailing-whitespace # Trims trailing whitespace.
        hook-stage: commit
  # yaml
  - repo: https://github.com/google/yamlfmt
    rev: v0.8.0
    hooks:
      - id: yamlfmt
        hook-stage: commit
  # python
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.0.267"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
        hook-stage: commit
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: [--config=./pyproject.toml]
        hook-stage: commit
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.18.0
    hooks:
      - id: stylua # or stylua-system / stylua-github
