{ lib
, stdenv
, fetchurl
, autoPatchelfHook
, wrapGAppsHook3
, makeDesktopItem
# Required library dependencies
, gtk3
, glib
, cairo
, pango
, atk
, gdk-pixbuf
, libnotify
, ayatana-ido
, libayatana-appindicator
, libdbusmenu-gtk3
, libX11
, libXext
, libXi
, libXfixes
, libXcursor
, libXdamage
, libXcomposite
, libXrandr
, libXinerama
, libXrender
, libxcb
, libxkbcommon
, wayland
, libepoxy
, at-spi2-core
, fontconfig
, freetype
, harfbuzz
, fribidi
, libthai
, graphite2
, libpng
, pixman
, lcms2
, libglycin
, json-glib
, libxml2
, sqlite
, tinysparql
, libcloudproviders
, icu
, zlib
, bzip2
, brotli
, pcre2
, libffi
, dbus
, libseccomp
, util-linux
, systemd
, dmidecode
, makeWrapper
}:

stdenv.mkDerivation rec {
  pname = "nfcloud";
  version = "latest"; # Upstream provides a fixed static URL for Linux binary updates

  # 1. Fetching the remote archive
  src = fetchurl {
    url = "https://backendoss.trafficmanager.net/api/v1/app/get/nfcloud/linux";
    name = "nfcloud-linux-1.4.9.tar.gz";
    hash = "sha256-Q+XHbL0k6NsiUkxvpQPQ959QFAPqHiuxrZ4LOI3rweQ=";
  };

  # Upstream archive lacks a top-level wrapper directory.
  # Set sourceRoot to current directory to prevent Nix from searching for a non-existent subdirectory.
  sourceRoot = ".";

  # 2. Build-time tools and hooks
  nativeBuildInputs = [
    autoPatchelfHook   # Automatically patches ELF binaries' RPATH to point into the Nix store
    wrapGAppsHook3     # Ensures GTK3 schemas, icons, themes, and GIO modules load properly at runtime
    makeWrapper
  ];

  # 3. Runtime dynamic library dependencies
  buildInputs = [
    gtk3 glib cairo pango atk gdk-pixbuf libnotify ayatana-ido libayatana-appindicator libdbusmenu-gtk3
    libX11 libXext libXi libXfixes libXcursor libXdamage libXcomposite libXrandr libXinerama libXrender
    libxcb libxkbcommon wayland libepoxy at-spi2-core fontconfig freetype harfbuzz fribidi libthai graphite2
    libpng pixman lcms2 libglycin json-glib libxml2 sqlite tinysparql libcloudproviders icu
    zlib bzip2 brotli pcre2 libffi dbus libseccomp util-linux systemd
    stdenv.cc.cc.lib   # Provides libstdc++.so.6 and libgcc_s.so.1
  ];

  # 4. Declarative Desktop Entry Generation via Pure Nix
  desktopItem = makeDesktopItem {
    name = "nfcloud";
    exec = "nfcloud";
    icon = "nfcloud";
    comment = "NFCLOUD Client";
    desktopName = "NFCLOUD";
    categories = [ "Network" ];
  };

  # 5. Installation phase
  installPhase = ''
    runHook preInstall

    # Leverage Bash brace expansion to create standard paths efficiently
    mkdir -p $out/{bin,libexec/nfcloud,share/applications,share/pixmaps}

    # Copy the unpacked Flutter bundle into the isolated internal libexec folder
    cp -r bundle/* $out/libexec/nfcloud/

    # Link the native desktop shortcut generated by pure Nix above
    cp ${desktopItem}/share/applications/* $out/share/applications/

    # Extract the app icon and place it into the system icon directory
    cp $out/libexec/nfcloud/data/flutter_assets/assets/icons/app_icon.png $out/share/pixmaps/nfcloud.png

    # Symlink strategy: Creating a native link instead of using heavy Bash makeWrapper scripts.
    # autoPatchelfHook will automatically trace this symlink, scan $out/libexec/nfcloud/lib,
    # and lock internal library paths directly into the executable's RPATH.
    ln -s $out/libexec/nfcloud/relayway $out/bin/nfcloud

    runHook postInstall
  '';

  postFixup = ''
  wrapProgram $out/bin/nfcloud \
      --prefix PATH : ${lib.makeBinPath [ dmidecode ]}
  '';

  meta = with lib; {
    description = "NFCLOUD Linux Desktop Client";
    homepage = "https://backendoss.trafficmanager.net";
    license = licenses.unfree; # Flagged as unfree since it's a proprietary precompiled client
    platforms = platforms.linux;
  };
}
