[theme]
theme = "slick"

[icons]
icons = "awesome4"

[[block]]
block = "net"
device = "utun"

[[block]]
block = "nvidia_gpu"

[[block]]
block = "memory"

[[block]]
block = "load"
format = "$1m.eng(w:4) $5m.eng(w:4) $15m.eng(w:4)"

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%F %a %T') "

[[block]]
block = "disk_space"
