theme = "slick"
icons = "awesome"

[[block]]
block = "net"

[[block]]
block = "nvidia_gpu"
label = "GTX 1080"

[[block]]
block = "memory"

[[block]]
block = "load"
format = "{1m} {5m} {15m}"

[[block]]
block = "time"
interval = 1
format = "%F %a %T"

[[block]]
block = "disk_space"
