server_endpoint = "/run/user/1000/clipcat/grpc.sock"
finder = "custom"
preview_length = 80
# Match the daemon's 40 MiB image limit.
grpc_max_message_size = 41943040

[log]
emit_journald = true
emit_stdout = false
emit_stderr = false
level = "INFO"

[custom_finder]
program = "walker"
args = ["--dmenu", "--exit", "--placeholder", "Clipcat"]
